- hosts: tomcat
  remote_user: ec2-user
  become: yes
  tasks:
  - name: upgrading all packages
    yum:
      name: 'yum'
      state: latest
  - name: installing Java 8
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Download Tomcat
    ansible.builtin.get_url: 
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.78/bin/apache-tomcat-9.0.78.tar.gz
      dest: /opt
      mode: '777'
  - name: Extract Tomcat link
    ansible.builtin.unarchive:
      src: /opt/apache-tomcat-9.0.78.tar.gz
      dest: /opt
      remote_src: yes
      mode: '777'
  - name: Starting Tomcat
    ansible.builtin.shell: nohup /opt/apache-tomcat-9.0.78/bin/startup.sh &

